// This file was generated by RedwoodJS
import FatalErrorPageType from '/Users/apple/redwoodblog/web/src/pages/FatalErrorPage/FatalErrorPage'
import NotFoundPageType from '/Users/apple/redwoodblog/web/src/pages/NotFoundPage/NotFoundPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const NotFoundPage: typeof NotFoundPageType
}

//# sourceMappingURL=web-routesPages.d.ts.map
